scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
scoreboard objectives add sos dummy
scoreboard objectives add sis dummy
