scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
scoreboard objectives add sas dummy
